In [505]:
import pandas as pd

# Putting NA for missing values

In [506]:
ccr = pd.read_csv('risk_factors_cervical_cancer.csv',na_values='?')

In [507]:
ccr.head()

,Age,Number of sexual partners,First sexual intercourse,Num of pregnancies,Smokes,Smokes (years),Smokes (packs/year),Hormonal Contraceptives,Hormonal Contraceptives (years),IUD,...,STDs: Time since first diagnosis,STDs: Time since last diagnosis,Dx:Cancer,Dx:CIN,Dx:HPV,Dx,Hinselmann,Schiller,Citology,Biopsy
0,18,4.0,15.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,0,0,0,0,0,0,0,0
1,15,1.0,14.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,0,0,0,0,0,0,0,0
2,34,1.0,NaN,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,0,0,0,0,0,0,0,0
3,52,5.0,16.0,4.0,1.0,37.0,37.0,1.0,3.0,0.0,...,NaN,NaN,1,0,1,0,0,0,0,0
4,46,3.0,21.0,4.0,0.0,0.0,0.0,1.0,15.0,0.0,...,NaN,NaN,0,0,0,0,0,0,0,0

# Drop Columns where NAs are 90%

In [508]:
ccr = ccr.loc[:,ccr.columns[ccr.isnull().sum() / ccr.shape[0] <= 0.9 ]]

In [509]:
ccr.count()

Age                                   858
Number of sexual partners             832
First sexual intercourse              851
Num of pregnancies                    802
Smokes                                845
Smokes (years)                        845
Smokes (packs/year)                   845
Hormonal Contraceptives               750
Hormonal Contraceptives (years)       750
IUD                                   741
IUD (years)                           741
STDs                                  753
STDs (number)                         753
STDs:condylomatosis                   753
STDs:cervical condylomatosis          753
STDs:vaginal condylomatosis           753
STDs:vulvo-perineal condylomatosis    753
STDs:syphilis                         753
STDs:pelvic inflammatory disease      753
STDs:genital herpes                   753
STDs:molluscum contagiosum            753
STDs:AIDS                             753
STDs:HIV                              753
STDs:Hepatitis B                      753
STDs:HPV                              753
STDs: Number of diagnosis             858
Dx:Cancer                             858
Dx:CIN                                858
Dx:HPV                                858
Dx                                    858
Hinselmann                            858
Schiller                              858
Citology                              858
Biopsy                                858
dtype: int64

In [510]:
ccr.head()

,Age,Number of sexual partners,First sexual intercourse,Num of pregnancies,Smokes,Smokes (years),Smokes (packs/year),Hormonal Contraceptives,Hormonal Contraceptives (years),IUD,...,STDs:HPV,STDs: Number of diagnosis,Dx:Cancer,Dx:CIN,Dx:HPV,Dx,Hinselmann,Schiller,Citology,Biopsy
0,18,4.0,15.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0,0,0,0,0,0,0,0,0
1,15,1.0,14.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0,0,0,0,0,0,0,0,0
2,34,1.0,NaN,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0,0,0,0,0,0,0,0,0
3,52,5.0,16.0,4.0,1.0,37.0,37.0,1.0,3.0,0.0,...,0.0,0,1,0,1,0,0,0,0,0
4,46,3.0,21.0,4.0,0.0,0.0,0.0,1.0,15.0,0.0,...,0.0,0,0,0,0,0,0,0,0,0

# Drop columns which are having strings or objects

In [511]:
ccr.dtypes

Age                                     int64
Number of sexual partners             float64
First sexual intercourse              float64
Num of pregnancies                    float64
Smokes                                float64
Smokes (years)                        float64
Smokes (packs/year)                   float64
Hormonal Contraceptives               float64
Hormonal Contraceptives (years)       float64
IUD                                   float64
IUD (years)                           float64
STDs                                  float64
STDs (number)                         float64
STDs:condylomatosis                   float64
STDs:cervical condylomatosis          float64
STDs:vaginal condylomatosis           float64
STDs:vulvo-perineal condylomatosis    float64
STDs:syphilis                         float64
STDs:pelvic inflammatory disease      float64
STDs:genital herpes                   float64
STDs:molluscum contagiosum            float64
STDs:AIDS                             float64
STDs:HIV                              float64
STDs:Hepatitis B                      float64
STDs:HPV                              float64
STDs: Number of diagnosis               int64
Dx:Cancer                               int64
Dx:CIN                                  int64
Dx:HPV                                  int64
Dx                                      int64
Hinselmann                              int64
Schiller                                int64
Citology                                int64
Biopsy                                  int64
dtype: object

In [512]:
ccr = ccr.select_dtypes(exclude=['object'])   #No object dtype here

In [513]:
ccr.head()

,Age,Number of sexual partners,First sexual intercourse,Num of pregnancies,Smokes,Smokes (years),Smokes (packs/year),Hormonal Contraceptives,Hormonal Contraceptives (years),IUD,...,STDs:HPV,STDs: Number of diagnosis,Dx:Cancer,Dx:CIN,Dx:HPV,Dx,Hinselmann,Schiller,Citology,Biopsy
0,18,4.0,15.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0,0,0,0,0,0,0,0,0
1,15,1.0,14.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0,0,0,0,0,0,0,0,0
2,34,1.0,NaN,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0,0,0,0,0,0,0,0,0
3,52,5.0,16.0,4.0,1.0,37.0,37.0,1.0,3.0,0.0,...,0.0,0,1,0,1,0,0,0,0,0
4,46,3.0,21.0,4.0,0.0,0.0,0.0,1.0,15.0,0.0,...,0.0,0,0,0,0,0,0,0,0,0

In [514]:
for col in ccr.columns:
    print(col, ccr[col].unique())

Age [18 15 34 52 46 42 51 26 45 44 27 43 40 41 39 37 38 36 35 33 31 32 30 23
 28 29 20 25 21 24 22 48 19 17 16 14 59 79 84 47 13 70 50 49]
Number of sexual partners [ 4.  1.  5.  3.  2.  6. nan  7. 15.  8. 10. 28.  9.]
First sexual intercourse [15. 14. nan 16. 21. 23. 17. 26. 20. 25. 18. 27. 19. 24. 32. 13. 29. 11.
 12. 22. 28. 10.]
Num of pregnancies [ 1.  4.  2.  6.  3.  5. nan  8.  7.  0. 11. 10.]
Smokes [ 0.  1. nan]
Smokes (years) [ 0.         37.         34.          1.26697291  3.         12.
         nan 18.          7.         19.         21.         15.
 13.         16.          8.          4.         10.         22.
 14.          0.5        11.          9.          2.          5.
  6.          1.         32.         24.         28.         20.
  0.16      ]
Smokes (packs/year) [0.00000000e+00 3.70000000e+01 3.40000000e+00 2.80000000e+00
 4.00000000e-02 5.13202128e-01 2.40000000e+00 6.00000000e+00
            nan 9.00000000e+00 1.60000000e+00 1.90000000e+01
 2.10000000e+01 3.20000000e-01 2.60000000e+00 8.00000000e-01
 1.50000000e+01 2.00000000e+00 5.70000000e+00 1.00000000e+00
 3.30000000e+00 3.50000000e+00 1.20000000e+01 2.50000000e-02
 2.75000000e+00 2.00000000e-01 1.40000000e+00 5.00000000e+00
 2.10000000e+00 7.00000000e-01 1.20000000e+00 7.50000000e+00
 1.25000000e+00 3.00000000e+00 7.50000000e-01 1.00000000e-01
 8.00000000e+00 2.25000000e+00 3.00000000e-03 7.00000000e+00
 4.50000000e-01 1.50000000e-01 5.00000000e-02 2.50000000e-01
 4.80000000e+00 4.50000000e+00 4.00000000e-01 3.70000000e-01
 2.20000000e+00 1.60000000e-01 9.00000000e-01 2.20000000e+01
 1.35000000e+00 5.00000000e-01 2.50000000e+00 4.00000000e+00
 1.30000000e+00 1.65000000e+00 2.70000000e+00 1.00000000e-03
 7.60000000e+00 5.50000000e+00 3.00000000e-01]
Hormonal Contraceptives [ 0.  1. nan]
Hormonal Contraceptives (years) [ 0.          3.         15.          2.          8.         10.
  5.          0.25        7.         22.         19.          0.5
  1.          0.58        9.         13.         11.          4.
 12.         16.          0.33               nan  0.16       14.
  0.08        2.28220052  0.66        6.          1.5         0.42
  0.67        0.75        2.5         4.5         6.5         0.17
 20.          3.5         0.41       30.         17.        ]
IUD [ 0.  1. nan]
IUD (years) [ 0.    7.     nan  5.    8.    6.    1.    0.58  2.   19.    0.5  17.
  0.08  0.25 10.   11.    3.   15.   12.    9.    1.5   0.91  4.    0.33
  0.41  0.16  0.17]
STDs [ 0.  1. nan]
STDs (number) [ 0.  2.  1. nan  3.  4.]
STDs:condylomatosis [ 0.  1. nan]
STDs:cervical condylomatosis [ 0. nan]
STDs:vaginal condylomatosis [ 0. nan  1.]
STDs:vulvo-perineal condylomatosis [ 0.  1. nan]
STDs:syphilis [ 0.  1. nan]
STDs:pelvic inflammatory disease [ 0. nan  1.]
STDs:genital herpes [ 0. nan  1.]
STDs:molluscum contagiosum [ 0. nan  1.]
STDs:AIDS [ 0. nan]
STDs:HIV [ 0.  1. nan]
STDs:Hepatitis B [ 0. nan  1.]
STDs:HPV [ 0. nan  1.]
STDs: Number of diagnosis [0 1 3 2]
Dx:Cancer [0 1]
Dx:CIN [0 1]
Dx:HPV [0 1]
Dx [0 1]
Hinselmann [0 1]
Schiller [0 1]
Citology [0 1]
Biopsy [0 1]

### converting columns where unique values are 3(0,1,NaN) to bool

In [515]:
for col in ccr.columns:
    if len(ccr[col].unique())<=3:
        ccr[col]=ccr[col].astype('bool')

In [516]:
ccr.dtypes

Age                                     int64
Number of sexual partners             float64
First sexual intercourse              float64
Num of pregnancies                    float64
Smokes                                   bool
Smokes (years)                        float64
Smokes (packs/year)                   float64
Hormonal Contraceptives                  bool
Hormonal Contraceptives (years)       float64
IUD                                      bool
IUD (years)                           float64
STDs                                     bool
STDs (number)                         float64
STDs:condylomatosis                      bool
STDs:cervical condylomatosis             bool
STDs:vaginal condylomatosis              bool
STDs:vulvo-perineal condylomatosis       bool
STDs:syphilis                            bool
STDs:pelvic inflammatory disease         bool
STDs:genital herpes                      bool
STDs:molluscum contagiosum               bool
STDs:AIDS                                bool
STDs:HIV                                 bool
STDs:Hepatitis B                         bool
STDs:HPV                                 bool
STDs: Number of diagnosis               int64
Dx:Cancer                                bool
Dx:CIN                                   bool
Dx:HPV                                   bool
Dx                                       bool
Hinselmann                               bool
Schiller                                 bool
Citology                                 bool
Biopsy                                   bool
dtype: object

In [517]:
for a in ccr.columns:
    print(ccr[a].dtypes)

int64
float64
float64
float64
bool
float64
float64
bool
float64
bool
float64
bool
float64
bool
bool
bool
bool
bool
bool
bool
bool
bool
bool
bool
bool
int64
bool
bool
bool
bool
bool
bool
bool
bool

## Print colmuns that have minimum one NaN value

In [518]:
#df.columns[df.isna().any()]
ccr.isna().any()

Age                                   False
Number of sexual partners              True
First sexual intercourse               True
Num of pregnancies                     True
Smokes                                False
Smokes (years)                         True
Smokes (packs/year)                    True
Hormonal Contraceptives               False
Hormonal Contraceptives (years)        True
IUD                                   False
IUD (years)                            True
STDs                                  False
STDs (number)                          True
STDs:condylomatosis                   False
STDs:cervical condylomatosis          False
STDs:vaginal condylomatosis           False
STDs:vulvo-perineal condylomatosis    False
STDs:syphilis                         False
STDs:pelvic inflammatory disease      False
STDs:genital herpes                   False
STDs:molluscum contagiosum            False
STDs:AIDS                             False
STDs:HIV                              False
STDs:Hepatitis B                      False
STDs:HPV                              False
STDs: Number of diagnosis             False
Dx:Cancer                             False
Dx:CIN                                False
Dx:HPV                                False
Dx                                    False
Hinselmann                            False
Schiller                              False
Citology                              False
Biopsy                                False
dtype: bool

In [519]:
ccr.describe()

,Age,Number of sexual partners,First sexual intercourse,Num of pregnancies,Smokes (years),Smokes (packs/year),Hormonal Contraceptives (years),IUD (years),STDs (number),STDs: Number of diagnosis
count,858.000000,832.000000,851.000000,802.000000,845.000000,845.000000,750.000000,741.000000,753.000000,858.000000
mean,26.820513,2.527644,16.995300,2.275561,1.219721,0.453144,2.256419,0.514804,0.176627,0.087413
std,8.497948,1.667760,2.803355,1.447414,4.089017,2.226610,3.764254,1.943089,0.561993,0.302545
min,13.000000,1.000000,10.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,20.000000,2.000000,15.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,25.000000,2.000000,17.000000,2.000000,0.000000,0.000000,0.500000,0.000000,0.000000,0.000000
75%,32.000000,3.000000,18.000000,3.000000,0.000000,0.000000,3.000000,0.000000,0.000000,0.000000
max,84.000000,28.000000,32.000000,11.000000,37.000000,37.000000,30.000000,19.000000,4.000000,3.000000

# Fill missing values Int or float values by median and bool by mode

In [520]:
for col in ccr.columns[ccr.isnull().any()]:
    if ccr[col].dtype != 'bool':
        ccr[col].fillna(ccr[col].median(),inplace=True)
    else:
        ccr[col].fillna(ccr[col].mode(),inplace=True)

In [521]:
ccr.head()

,Age,Number of sexual partners,First sexual intercourse,Num of pregnancies,Smokes,Smokes (years),Smokes (packs/year),Hormonal Contraceptives,Hormonal Contraceptives (years),IUD,...,STDs:HPV,STDs: Number of diagnosis,Dx:Cancer,Dx:CIN,Dx:HPV,Dx,Hinselmann,Schiller,Citology,Biopsy
0,18,4.0,15.0,1.0,False,0.0,0.0,False,0.0,False,...,False,0,False,False,False,False,False,False,False,False
1,15,1.0,14.0,1.0,False,0.0,0.0,False,0.0,False,...,False,0,False,False,False,False,False,False,False,False
2,34,1.0,17.0,1.0,False,0.0,0.0,False,0.0,False,...,False,0,False,False,False,False,False,False,False,False
3,52,5.0,16.0,4.0,True,37.0,37.0,True,3.0,False,...,False,0,True,False,True,False,False,False,False,False
4,46,3.0,21.0,4.0,False,0.0,0.0,True,15.0,False,...,False,0,False,False,False,False,False,False,False,False

In [522]:
ccr.describe()

,Age,Number of sexual partners,First sexual intercourse,Num of pregnancies,Smokes (years),Smokes (packs/year),Hormonal Contraceptives (years),IUD (years),STDs (number),STDs: Number of diagnosis
count,858.000000,858.000000,858.000000,858.000000,858.000000,858.000000,858.000000,858.000000,858.000000,858.000000
mean,26.820513,2.511655,16.995338,2.257576,1.201241,0.446278,2.035331,0.444604,0.155012,0.087413
std,8.497948,1.644759,2.791883,1.400981,4.060623,2.210351,3.567040,1.814218,0.529617,0.302545
min,13.000000,1.000000,10.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,20.000000,2.000000,15.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,25.000000,2.000000,17.000000,2.000000,0.000000,0.000000,0.500000,0.000000,0.000000,0.000000
75%,32.000000,3.000000,18.000000,3.000000,0.000000,0.000000,2.000000,0.000000,0.000000,0.000000
max,84.000000,28.000000,32.000000,11.000000,37.000000,37.000000,30.000000,19.000000,4.000000,3.000000

In [523]:
ccr.describe(include = 'all')

,Age,Number of sexual partners,First sexual intercourse,Num of pregnancies,Smokes,Smokes (years),Smokes (packs/year),Hormonal Contraceptives,Hormonal Contraceptives (years),IUD,...,STDs:HPV,STDs: Number of diagnosis,Dx:Cancer,Dx:CIN,Dx:HPV,Dx,Hinselmann,Schiller,Citology,Biopsy
count,858.000000,858.000000,858.000000,858.000000,858,858.000000,858.000000,858,858.000000,858,...,858,858.000000,858,858,858,858,858,858,858,858
unique,NaN,NaN,NaN,NaN,2,NaN,NaN,2,NaN,2,...,2,NaN,2,2,2,2,2,2,2,2
top,NaN,NaN,NaN,NaN,False,NaN,NaN,True,NaN,False,...,False,NaN,False,False,False,False,False,False,False,False
freq,NaN,NaN,NaN,NaN,722,NaN,NaN,589,NaN,658,...,751,NaN,840,849,840,834,823,784,814,803
mean,26.820513,2.511655,16.995338,2.257576,NaN,1.201241,0.446278,NaN,2.035331,NaN,...,NaN,0.087413,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,8.497948,1.644759,2.791883,1.400981,NaN,4.060623,2.210351,NaN,3.567040,NaN,...,NaN,0.302545,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,13.000000,1.000000,10.000000,0.000000,NaN,0.000000,0.000000,NaN,0.000000,NaN,...,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,20.000000,2.000000,15.000000,1.000000,NaN,0.000000,0.000000,NaN,0.000000,NaN,...,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,25.000000,2.000000,17.000000,2.000000,NaN,0.000000,0.000000,NaN,0.500000,NaN,...,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,32.000000,3.000000,18.000000,3.000000,NaN,0.000000,0.000000,NaN,2.000000,NaN,...,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,84.000000,28.000000,32.000000,11.000000,NaN,37.000000,37.000000,NaN,30.000000,NaN,...,NaN,3.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [524]:
ccr.columns[ccr.isnull().any()]

Index([], dtype='object')

In [525]:
ccr.head()

,Age,Number of sexual partners,First sexual intercourse,Num of pregnancies,Smokes,Smokes (years),Smokes (packs/year),Hormonal Contraceptives,Hormonal Contraceptives (years),IUD,...,STDs:HPV,STDs: Number of diagnosis,Dx:Cancer,Dx:CIN,Dx:HPV,Dx,Hinselmann,Schiller,Citology,Biopsy
0,18,4.0,15.0,1.0,False,0.0,0.0,False,0.0,False,...,False,0,False,False,False,False,False,False,False,False
1,15,1.0,14.0,1.0,False,0.0,0.0,False,0.0,False,...,False,0,False,False,False,False,False,False,False,False
2,34,1.0,17.0,1.0,False,0.0,0.0,False,0.0,False,...,False,0,False,False,False,False,False,False,False,False
3,52,5.0,16.0,4.0,True,37.0,37.0,True,3.0,False,...,False,0,True,False,True,False,False,False,False,False
4,46,3.0,21.0,4.0,False,0.0,0.0,True,15.0,False,...,False,0,False,False,False,False,False,False,False,False

# Merging all the target variables into 1

In [526]:
ccr['target'] = ccr.iloc[:,-1] | ccr.iloc[:,-2] | ccr.iloc[:,-3] | ccr.iloc[:,-4]

In [527]:
ccr['target'].unique()

array([False,  True])

In [528]:
ccr.head()

,Age,Number of sexual partners,First sexual intercourse,Num of pregnancies,Smokes,Smokes (years),Smokes (packs/year),Hormonal Contraceptives,Hormonal Contraceptives (years),IUD,...,STDs: Number of diagnosis,Dx:Cancer,Dx:CIN,Dx:HPV,Dx,Hinselmann,Schiller,Citology,Biopsy,target
0,18,4.0,15.0,1.0,False,0.0,0.0,False,0.0,False,...,0,False,False,False,False,False,False,False,False,False
1,15,1.0,14.0,1.0,False,0.0,0.0,False,0.0,False,...,0,False,False,False,False,False,False,False,False,False
2,34,1.0,17.0,1.0,False,0.0,0.0,False,0.0,False,...,0,False,False,False,False,False,False,False,False,False
3,52,5.0,16.0,4.0,True,37.0,37.0,True,3.0,False,...,0,True,False,True,False,False,False,False,False,False
4,46,3.0,21.0,4.0,False,0.0,0.0,True,15.0,False,...,0,False,False,False,False,False,False,False,False,False

## Removing the 4 target variables (Hinselmann	Schiller	Citology	Biopsy)

In [529]:
ccr.drop(ccr.iloc[:,-5:-1],axis =1,inplace=True)

In [530]:
ccr.head()

,Age,Number of sexual partners,First sexual intercourse,Num of pregnancies,Smokes,Smokes (years),Smokes (packs/year),Hormonal Contraceptives,Hormonal Contraceptives (years),IUD,...,STDs:AIDS,STDs:HIV,STDs:Hepatitis B,STDs:HPV,STDs: Number of diagnosis,Dx:Cancer,Dx:CIN,Dx:HPV,Dx,target
0,18,4.0,15.0,1.0,False,0.0,0.0,False,0.0,False,...,False,False,False,False,0,False,False,False,False,False
1,15,1.0,14.0,1.0,False,0.0,0.0,False,0.0,False,...,False,False,False,False,0,False,False,False,False,False
2,34,1.0,17.0,1.0,False,0.0,0.0,False,0.0,False,...,False,False,False,False,0,False,False,False,False,False
3,52,5.0,16.0,4.0,True,37.0,37.0,True,3.0,False,...,False,False,False,False,0,True,False,True,False,False
4,46,3.0,21.0,4.0,False,0.0,0.0,True,15.0,False,...,False,False,False,False,0,False,False,False,False,False

## checking for all rows having same values

In [540]:
(ccr.iloc[0] == ccr).all()

Age                                   False
Number of sexual partners             False
First sexual intercourse              False
Num of pregnancies                    False
Smokes                                False
Smokes (years)                        False
Smokes (packs/year)                   False
Hormonal Contraceptives               False
Hormonal Contraceptives (years)       False
IUD                                   False
IUD (years)                           False
STDs                                  False
STDs (number)                         False
STDs:condylomatosis                   False
STDs:cervical condylomatosis          False
STDs:vaginal condylomatosis           False
STDs:vulvo-perineal condylomatosis    False
STDs:syphilis                         False
STDs:pelvic inflammatory disease      False
STDs:genital herpes                   False
STDs:molluscum contagiosum            False
STDs:AIDS                             False
STDs:HIV                              False
STDs:Hepatitis B                      False
STDs:HPV                              False
STDs: Number of diagnosis             False
Dx:Cancer                             False
Dx:CIN                                False
Dx:HPV                                False
Dx                                    False
target                                False
dtype: bool

# Normalizing data using Min Max scaler

In [532]:
from sklearn import preprocessing

In [533]:
x = ccr.values #returns a numpy array
x

array([[18, 4.0, 15.0, ..., False, False, False],
       [15, 1.0, 14.0, ..., False, False, False],
       [34, 1.0, 17.0, ..., False, False, False],
       ...,
       [25, 2.0, 17.0, ..., False, False, True],
       [33, 2.0, 24.0, ..., False, False, False],
       [29, 2.0, 20.0, ..., False, False, False]], dtype=object)

In [534]:
min_max_scaler = preprocessing.MinMaxScaler()
min_max_scaler

MinMaxScaler()

In [535]:
x_scaled = min_max_scaler.fit_transform(x)
x_scaled

array([[0.07042254, 0.11111111, 0.22727273, ..., 0.        , 0.        ,
        0.        ],
       [0.02816901, 0.        , 0.18181818, ..., 0.        , 0.        ,
        0.        ],
       [0.29577465, 0.        , 0.31818182, ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.16901408, 0.03703704, 0.31818182, ..., 0.        , 0.        ,
        1.        ],
       [0.28169014, 0.03703704, 0.63636364, ..., 0.        , 0.        ,
        0.        ],
       [0.22535211, 0.03703704, 0.45454545, ..., 0.        , 0.        ,
        0.        ]])

In [536]:
ccr = pd.DataFrame(x_scaled,columns=ccr.columns)

In [537]:
ccr.describe(include= 'all')

,Age,Number of sexual partners,First sexual intercourse,Num of pregnancies,Smokes,Smokes (years),Smokes (packs/year),Hormonal Contraceptives,Hormonal Contraceptives (years),IUD,...,STDs:AIDS,STDs:HIV,STDs:Hepatitis B,STDs:HPV,STDs: Number of diagnosis,Dx:Cancer,Dx:CIN,Dx:HPV,Dx,target
count,858.000000,858.000000,858.000000,858.000000,858.000000,858.000000,858.000000,858.000000,858.000000,858.000000,...,858.000000,858.000000,858.000000,858.000000,858.000000,858.000000,858.000000,858.000000,858.000000,858.000000
mean,0.194655,0.055987,0.317970,0.205234,0.158508,0.032466,0.012062,0.686480,0.067844,0.233100,...,0.122378,0.143357,0.123543,0.124709,0.029138,0.020979,0.010490,0.020979,0.027972,0.118881
std,0.119689,0.060917,0.126904,0.127362,0.365430,0.109747,0.059739,0.464194,0.118901,0.423052,...,0.327913,0.350641,0.329252,0.330581,0.100848,0.143398,0.101939,0.143398,0.164989,0.323837
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.098592,0.037037,0.227273,0.090909,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.169014,0.037037,0.318182,0.181818,0.000000,0.000000,0.000000,1.000000,0.016667,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,0.267606,0.074074,0.363636,0.272727,0.000000,0.000000,0.000000,1.000000,0.066667,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [539]:
# Save the new cleaned data
ccr.to_csv("cleaned_riskfactor_cervical_cancer.csv",index=False)